<section id="table-user">

    <div class="page-header">
        <h1>User Information</h1>
    </div>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th style="width:150px">Topic</th>
                <th>Content</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>ID</td>
                <td><?php echo $user->getId(); ?></td>
            </tr>
            <tr>
                <td>Account</td>
                <td><?php echo $user->getAccount(); ?></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><?php echo $user->getEmail(); ?></td>
            </tr>
            <tr>
                <td>Role </td>
                <td><?php echo join(", ", $user->getRoleDescriptions() ); ?></td>
            </tr>
            <tr>
                <td>Modify my password</td>
                <td><a href="<?php echo url('me/password'); ?>">edit</a></td>
            </tr>
            <?php
                if( UserManager::isAdmin() ) {
                    if( UserManager::isDebugMode() ) {
                        $text = '切換為一般模式';
                        $changeEnvironmentUrl = url('me/changeEnvironment', array('isDeveloper'=>0) );
                    }
                    else {
                        $text = '切換為開發模式';
                        $changeEnvironmentUrl = url('me/changeEnvironment', array('isDeveloper'=>1) );
                    }
            ?>
                <tr>
                    <td>開發環境</td>
                    <td><a href="<?php echo $changeEnvironmentUrl; ?>"><?php echo $text; ?></a></td>
                </tr>
            <?php
                }
            ?>
        </tbody>
    </table>

</section>



<?php
    if( UserManager::isDebugMode() ) {
        echo '<ul>';
        echo '<li>class name = '. get_class($this) .'</li>';
        echo '<li>__FILE__ = '.   __FILE__ .'</li>';
        echo '<li>login_user_info_string = '. SessionBrg::get('login_user_info_string') .'</li>';
        echo '</ul>';

        // $cartUrl = 'http://' . $_SERVER['HTTP_HOST'] . APPLICATION_SHOP_URI . '/cart.php';
        // $cartContent = file_get_contents($cartUrl);
        // echo $cartContent;

        echo '<pre style="color:#000;text-align:left;font-size:10px;font-family:dina,GulimChe;">'; print_r( $_SESSION ); echo "</pre>\n";
    }



