
<form class="well" method="post">

    <div class="form-group">
        <label for="account">Your Account</label>
        <input type="text" class="form-control" name="account" value="<?php echo $user->getAccount(); ?>" disabled="disabled" />
    </div>

    <div class="form-group <?php echo FormMessageManager::getFieldStatus('password'); ?>">
        <label for="password">* New Password</label>
        <input type="password" class="form-control" name="password" />
        <?php if( $message = FormMessageManager::getFieldMessage('password') ): ?>
            <p class="help-block"><?php echo $message; ?></p>
        <?php endif ?>
    </div>

    <div class="form-group <?php echo FormMessageManager::getFieldStatus('password2'); ?>">
        <label for="password2">* Confirm New Password</label>
        <input type="password" class="form-control" name="password2" />
        <?php if( $message = FormMessageManager::getFieldMessage('password2') ): ?>
            <p class="help-block"><?php echo $message; ?></p>
        <?php endif ?>
    </div>

    <div class="form-group <?php echo FormMessageManager::getFieldStatus('oldPassword'); ?>">
        <label for="oldPassword">* Old Password</label>
        <input type="password" class="form-control" name="oldPassword" />
        <?php if( $message = FormMessageManager::getFieldMessage('oldPassword') ): ?>
            <p class="help-block"><?php echo $message; ?></p>
        <?php endif ?>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>
