
<form class="well" method="post">

    <div class="row">

        <div class="col-md-12">
            密碼結構的建議
            <ol>
                <li>密碼要很長, 以避免被暴力破解</li>
                <li>符合以上要點, 密碼包含英文, 數字, 符號</li>
                <li>符合以上要點, 每個月都修改一次密碼</li>
                <li>密碼可以是有意義, 可理解之文字</li>
                <li>Example: "I never think of the future. It comes soon enough. - Albert Einstein, 1879/3/14"</li>
            </ol>
        </div>

    </div>

    <div class="form-group">
        <label for="account">Your Account</label>
        <input type="text" class="form-control" name="account" value="<?php echo $user->getAccount(); ?>" disabled="disabled" />
    </div>

    <div class="form-group <?php echo FormMessageManager::getFieldStatus('password'); ?>">
        <label for="password">* New Password</label>
        <input type="password" class="form-control" name="password" />
        <?php if( $message = FormMessageManager::getFieldMessage('password') ): ?>
            <p class="help-block"><?php echo $message; ?></p>
        <?php endif ?>
    </div>

    <div class="form-group <?php echo FormMessageManager::getFieldStatus('password2'); ?>">
        <label for="password2">* Confirm New Password</label>
        <input type="password" class="form-control" name="password2" />
        <?php if( $message = FormMessageManager::getFieldMessage('password2') ): ?>
            <p class="help-block"><?php echo $message; ?></p>
        <?php endif ?>
    </div>

    <div class="form-group <?php echo FormMessageManager::getFieldStatus('oldPassword'); ?>">
        <label for="oldPassword">* Old Password</label>
        <input type="password" class="form-control" name="oldPassword" />
        <?php if( $message = FormMessageManager::getFieldMessage('oldPassword') ): ?>
            <p class="help-block"><?php echo $message; ?></p>
        <?php endif ?>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>
