<?php

    $version = '?';
    if ( function_exists('gearman_version') ) {
        $version = gearman_version();
    }

    $isLoaded = 'No';
    if ( extension_loaded('gearman') ) {
        $isLoaded = 'Yes';
    }

?>

    <h1><?php echo $label; ?></h1>
    <hr/>

    <div class="form-group">
        <label for="">Load Gearman extension</label>
        <pre><?php echo $isLoaded; ?></pre>
    </div>

    <div class="form-group">
        <label for="">Gearman version</label>
        <pre><?php echo $version; ?></pre>
    </div>

    <div class="form-group">
        <label for="">ps ax | grep gearmand</label>
        <pre><?php echo exec('ps ax | grep gearmand'); ?></pre>
    </div>
