
    <h1><?php echo $label; ?></h1>
    <hr/>

    <form name="form-setting" id="form-setting" class="well" method="post">

        <div class="row">

            <div class="col-md-12">
                <label>Input passwd</label>
                <div class="form-group">
                    <input type="text" class="form-control" name="passwd" placeholder="" />
                    <p class="help-block"><?php echo $result; ?></p>
                </div>
            </div>

            <div class="col-md-12">
                密碼建議
                <ul>
                    <li>1. 密碼要很長, 以避免暴力破解</li>
                    <li>2. 符合要點 1, 密碼可以是有意義, 可理解之文字</li>
                    <li>3. 符合要點 2, 每一個月都修改一次密碼</li>
                    <li>舉例: 『前不見古人,後不見來者,念天地之悠悠,獨愴然而涕下.2000-12-31』</li>
                </ul>
            </div>

            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">TRY IT</button>
            </div>

        </div>

    </form>

