
    <h1><?php echo $label; ?></h1>
    <hr/>

    <form name="form-setting" id="form-setting" class="well" method="post">

        <div class="row">

            <div class="col-md-12">
                <label>Input passwd</label>
                <div class="form-group">
                    <input type="text" class="form-control" name="passwd" placeholder="" />
                    <p class="help-block"><?php echo $result; ?></p>
                </div>
            </div>

            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">try it</button>
            </div>

        </div>

    </form>

