<?php

    $isLoaded = 'No';
    $version = '?';
    if ( extension_loaded('phalcon') ) {

        $isLoaded = 'Yes';
        $version = Phalcon\Version::get();

    }

?>

    <h1><?php echo $label; ?></h1>
    <hr/>

    <div class="form-group">
        <label for="">Load Phalcon extension</label>
        <pre><?php echo $isLoaded; ?></pre>
    </div>

    <div class="form-group">
        <label for="">Phalcon version</label>
        <pre><?php echo $version; ?></pre>
    </div>
