<?php
    $homeUri = url('');
?>
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo RegisterManager::get('title'); ?></title>
        <meta name="description" content="">
        <?php $this->assets->outputCss() ?>
        <?php $this->assets->outputJs() ?>
        <script type="text/javascript">
        </script>
    </head>
    <body>

        <nav>
            <div class="navbar navbar-inverse navbar-static-top">
                <div class="container">
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="<?php echo $homeUri; ?>">Go Homepage</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </nav>

        <div class="container">
            <h1>
                Page Not Found
            </h1>
        </div>

        <div class="container">
            <?php echo $this->getContent() ?>
        </div>

    </body>
</html>