<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?php echo RegisterManager::get('title'); ?></title>
        <meta name="description" content="">
        <?php $this->assets->outputCss() ?>
        <?php $this->assets->outputJs() ?>
        <script type="text/javascript">
        </script>
    </head>
    <body>
        <nav>
            <?php echo block('Navigation'); ?>
        </nav>
        <div class="container-fluid" >

            <div class="row">
                <div class="col-md-2">
                    <?php echo block('SubMenu'); ?>
                </div>
                <div class="col-md-10">

                    <div class="row">
                        <div class="col-md-12">
                            <?php echo block('FormMessage'); ?>
                        </div>
                    </div>

                    <?php echo $this->getContent() ?>

                </div>
            </div>

        </div>
    </body>
</html>