<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?php echo RegisterManager::get('title'); ?></title>
        <meta name="keywords" content=private" />  
        <meta name="description" content="private page" />
        <meta name="robots" content="noindex,nofollow" /> 
        <?php $this->assets->outputCss() ?>
        <?php $this->assets->outputJs() ?>
        <script type="text/javascript">
        </script>
    </head>
    <body>
        <div class="container">
            <?php echo $this->getContent() ?>
        </div>
    </body>
</html>